---
openapi: 3.0.2
info:
  title: Creature API
  description: This is the API of the Match service
  contact:
    email: mohamed.dallel@imt-atlantique.net
  license:
    name: GPL v3
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: 1.0.0
tags:
- name: admins
  description: Secured Admin-only calls
- name: users
  description: Operations available to regular users
paths:
  /api/match/create:
    post:
      tags:
      - users
      summary: create a match
      description: |
        By passing in the appropriate options, you can create a match
      requestBody:
        description: IDs of users
        content:
          application/json:
            schema:
              required:
              - player_1_id
              type: object
              properties:
                player_1_id:
                  type: integer
                  example: 5620
                player_2_id:
                  type: integer
                  example: 4126
      responses:
        "200":
          description: match created
        "400":
          description: bad input parameter
  /api/match/get:
    get:
      tags:
      - users
      summary: get information of a match
      description: |
        By passing in the appropriate options, you can get information of a match
      parameters:
      - name: matchId
        in: query
        description: match ID.
        required: true
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Return information of match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/match'
        "400":
          description: bad input parameter
  /api/match/join:
    put:
      tags:
      - users
      summary: join to a match
      description: |
        By passing in the appropriate options, you can join to a match
      requestBody:
        description: matchId and userId
        content:
          application/json:
            schema:
              required:
              - matchId
              - userId
              type: object
              properties:
                matchId:
                  type: integer
                  example: 1407
                userId:
                  type: integer
                  example: 5062
      responses:
        "200":
          description: joined to the match
        "400":
          description: bad input parameter
  /api/match/send-creature:
    put:
      tags:
      - users
      summary: send a creature to the arena
      description: |
        By passing in the appropriate options, you can send a creature to the arena
      requestBody:
        description: matchId, userId and creatureId
        content:
          application/json:
            schema:
              required:
              - userId
              - matchId
              - creatureId
              type: object
              properties:
                userId:
                  type: integer
                  example: 5062
                matchId:
                  type: integer
                  example: 140799
                creatureId:
                  type: integer
                  example: 123
      responses:
        "200":
          description: sent creature
        "400":
          description: bad input parameter
  /api/match/get-round:
    get:
      tags:
      - users
      summary: get information of a match round
      description: |
        By passing in the appropriate options, you can get information of a match round
      parameters:
      - name: matchId
        in: query
        description: match ID.
        required: true
        explode: false
        schema:
          type: string
      - name: round_number
        in: query
        description: integer round.
        required: true
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: Information of a match
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Round'
        "400":
          description: bad input parameter
  /api/match/list:
    get:
      tags:
      - admins
      summary: get list of matches
      description: |
        You can get list of matches
      responses:
        "200":
          description: List of matches
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/matchs'
        "400":
          description: bad input parameter
  /api/match/delete:
    delete:
      tags:
      - users
      summary: delete a match
      description: |
        By passing in the appropriate options, you can delete a match
      parameters:
      - name: matchId
        in: query
        description: match ID.
        required: true
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: match deleted
        "400":
          description: bad input parameter
components:
  schemas:
    matchs:
      type: array
      items:
        $ref: '#/components/schemas/match'

    match:
      required:
      - id
      - player_1_id
      - player_2_id
      - state
      - start_date
      - rounds
      type: object
      properties:
        id:
          type: integer
          example: 1102
        player_1_id:
          type: integer
          example: 5620
        player_2_id:
          type: integer
          example: 4126
        winner_id:
          type: integer
          example: 5620
        state:
          type: string
          example: "in progress"
        currentRound:
          type: integer
          example: 2
        start_date:
          type: string
          example: "2023-11-12T21:41:21.007Z"
        end_date:
          type: string
          example: "2023-11-12T22:31:18.007Z"
        rounds:
          type: array
          items:
            $ref: '#/components/schemas/Round'
    
    Round:
      type: object
      properties:
        id:
          type: integer
          example: 6059
        match_id:
          type: integer
          example: 1102
        round_number:         
          type: integer
          description: "1 to 5"
          example: 3
        creature_p1_id:
          type: integer
          example: 1612
        creature_p2_id:
          type: integer
          example: 2105
        winner:         
          type: integer
          description: "1 if player 1 won, 2 otherwise"
          example: 1
    